#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# MemoLink — API key generator
#
# Usage:
#   ./scripts/generate-keys.sh              # writes to ~/.memolink/.env
#   ./scripts/generate-keys.sh /custom/path # writes to a custom path
#
# The script is idempotent: it does NOT overwrite existing keys.
# Run with --force to regenerate all keys.
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

ENV_FILE="${1:-$HOME/.memolink/.env}"
FORCE=false
[[ "${1:-}" == "--force" ]] && FORCE=true && ENV_FILE="${2:-$HOME/.memolink/.env}"

# ── Key generation ────────────────────────────────────────────────────────────
gen_key() {
    local prefix="$1"
    if command -v openssl &>/dev/null; then
        echo "${prefix}-$(openssl rand -base64 24 | tr -d '=+/')"
    elif command -v python3 &>/dev/null; then
        echo "${prefix}-$(python3 -c 'import secrets; print(secrets.token_urlsafe(24))')"
    else
        echo "${prefix}-$(uuidgen | tr -d '-' | tr '[:upper:]' '[:lower:]')"
    fi
}

# ── Bootstrap env file ────────────────────────────────────────────────────────
mkdir -p "$(dirname "$ENV_FILE")"
chmod 700 "$(dirname "$ENV_FILE")"

if [[ -f "$ENV_FILE" && "$FORCE" == "false" ]]; then
    echo "Existing .env found at $ENV_FILE"
    echo "Keeping existing keys. Run with --force to regenerate all."
    echo ""
    # Add any missing keys without touching existing ones
    add_if_missing() {
        local key="$1" value="$2"
        if ! grep -q "^${key}=" "$ENV_FILE"; then
            echo "${key}=${value}" >> "$ENV_FILE"
            echo "  Added: ${key}"
        else
            echo "  Kept:  ${key}"
        fi
    }
else
    if [[ -f "$ENV_FILE" ]]; then
        cp "$ENV_FILE" "${ENV_FILE}.bak"
        echo "Backed up existing .env to ${ENV_FILE}.bak"
    fi
    # Write fresh file
    cat > "$ENV_FILE" << ENVEOF
# MemoLink environment — keep this file secret, never commit it
# Generated by generate-keys.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

MEMOLINK_NOTES_DIR=${MEMOLINK_NOTES_DIR:-$HOME/notes}
MEMOLINK_HTTP_PORT=${MEMOLINK_HTTP_PORT:-8765}
ENVEOF
    chmod 600 "$ENV_FILE"

    add_if_missing() {
        local key="$1" value="$2"
        echo "${key}=${value}" >> "$ENV_FILE"
        echo "  Generated: ${key}"
    }
fi

echo ""
echo "── Generating API keys ──────────────────────────────────────"
add_if_missing "MEMOLINK_KEY_VSCODE" "$(gen_key sk-vscode)"
add_if_missing "MEMOLINK_KEY_CLAUDE" "$(gen_key sk-claude)"
add_if_missing "MEMOLINK_KEY_CI"     "$(gen_key sk-ci)"

chmod 600 "$ENV_FILE"

echo ""
echo "── Done ─────────────────────────────────────────────────────"
echo "Keys stored at: $ENV_FILE"
echo ""
echo "Your keys (keep these secret):"
echo ""
grep "^MEMOLINK_KEY_" "$ENV_FILE"
echo ""
echo "Next steps:"
echo "  1. source $ENV_FILE"
echo "  2. Start HTTP mode: java --enable-native-access=ALL-UNNAMED \\"
echo "       -jar memolink-mcp-server/target/memolink-mcp-server-0.1.0-SNAPSHOT.jar \\"
echo "       --spring.profiles.active=http"
echo "  3. Add the key to your client config (see MCP-USAGE.md)"
